<a href="https://colab.research.google.com/github/ziba18/PyTorch-Jovian-assignments/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('16xtjbVK8IQlCvg6BN3EJ6-kkleTDOa1N')

     |████████████████████████████████| 68 kB 1.6 MB/s 


> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# 5 PyTorch functions you didn't know you needed

An short introduction about PyTorch : 
and about the chosen functions. 

- movedim
- TORCH.TENSOR.SCATTER_ADD_
- t
- tensor_split
- initial_seed

Before we begin, let's install and import PyTorch

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - movedim

Moves the dimension(s) of input at the position(s) in source to the position(s) in destination.

> 




torch.movedim(input, source, destination) → Tensor

In [ ]:
# Example 1 - working

mytensor = torch.randn(3,6)
print(mytensor)

t_md = torch.movedim(mytensor, -2, 0)
print(t_md.size)
print(t_md)

tensor([[ 0.3876,  0.2354, -0.2845, -0.5469, -0.2393, -0.0101],
        [-0.9966, -1.8653, -0.0044,  1.0036, -0.6072, -0.4742],
        [ 1.4653, -0.9136,  0.1436, -0.7575,  0.7051, -1.0009]])
<built-in method size of Tensor object at 0x7f6f7ac0a8f0>
tensor([[ 0.3876,  0.2354, -0.2845, -0.5469, -0.2393, -0.0101],
        [-0.9966, -1.8653, -0.0044,  1.0036, -0.6072, -0.4742],
        [ 1.4653, -0.9136,  0.1436, -0.7575,  0.7051, -1.0009]])


Explanation about example: The original positions of the dims is moved to the destination position. Therefore 

In [ ]:
# Example 2 - working

mytensor = torch.tensor([[1, 2, 6], [3, 4.,5]])
t_md = torch.movedim(mytensor, 0, 1)
t_md

tensor([[1., 3.],
        [2., 4.],
        [6., 5.]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
mytensor = torch.tensor([[1, 2], [3, 4]])
t_md = torch.movedim(mytensor, 0, 5)
t_md

ValueError: ignored

Explanation about example

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/zamaniziba18/01-tensor-operations


'https://jovian.ai/zamaniziba18/01-tensor-operations'

## Function 2 - TORCH.TENSOR.SCATTER_ADD_


Adds all values from the tensor src into self at the indices specified in the index tensor in a similar fashion as scatter_(). 
>For each value in src, it is added to an index in self which is specified by its index in src for dimension != dim and by the corresponding value in index for dimension = dim.





In [ ]:
# Example 1 - working

myTensor = torch.tensor([[1,2], [3,4]])
myTensor

torch.select(myTensor, 1,1)

tensor([2, 4])

Explanation about example

In [ ]:
# Example 2 - working

myTensor = torch.randn(3,6)
myTensor

torch.select(myTensor, 1,5)

tensor([-1.4105, -1.1902,  0.0382])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

myTensor = torch.tensor([[1,2], [3,4]])
myTensor

torch.select(myTensor, 1,2)

IndexError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/zamaniziba18/01-tensor-operations


'https://jovian.ai/zamaniziba18/01-tensor-operations'

## Function 3 - t

Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.

In [ ]:
# Example 1 - working

x = torch.randn(())
print(x)
print(torch.t(x))

tensor(-0.5021)
tensor(-0.5021)


0-D and 1-D tensors are returned as is.

In [ ]:
# Example 2 - working

x = torch.randn((2,3))
print(x)
print(torch.t(x))

tensor([[ 0.4154,  0.5991, -0.7656],
        [-1.7860,  0.7982, -0.8711]])
tensor([[ 0.4154, -1.7860],
        [ 0.5991,  0.7982],
        [-0.7656, -0.8711]])


 When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.randn((2,3,5))
print(x)
print(torch.t(x))

tensor([[[-0.9312,  1.1201,  1.7391, -0.5414,  1.7775],
         [-1.2846, -0.0932,  1.2058, -0.3252,  0.0939],
         [-0.4343, -1.0436, -0.0496,  0.0063, -1.2822]],

        [[ 0.8994,  0.1366,  0.5491,  0.4846, -2.1185],
         [-1.5202,  1.3152,  0.9631, -0.2550,  1.5508],
         [ 0.2520, -0.6820, -1.5246, -0.5934,  0.8514]]])


RuntimeError: ignored

t() expects a tensor with <= 2 dimensions, but self is 3D

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/zamaniziba18/01-tensor-operations


'https://jovian.ai/zamaniziba18/01-tensor-operations'

## Function 4 - tensor_split

Splits a tensor into multiple sub-tensors, all of which are views of input, along dimension dim according to the indices or number of sections specified by indices_or_sections. This function is based on NumPy’s numpy.array_split().

>input (Tensor) – the tensor to split

indices_or_sections (Tensor, int or list or tuple of ints) –

If indices_or_sections is an integer n or a zero dimensional long tensor with value n, input is split into n sections along dimension dim. If input is divisible by n along dimension dim, each section will be of equal size, input.size(dim) / n. If input is not divisible by n, the sizes of the first int(input.size(dim) % n) sections will have size int(input.size(dim) / n) + 1, and the rest will have size int(input.size(dim) / n).

If indices_or_sections is a list or tuple of ints, or a one-dimensional long tensor, then input is split along dimension dim at each of the indices in the list, tuple or tensor. For instance, indices_or_sections=[2, 3] and dim=0 would result in the tensors input[:2], input[2:3], and input[3:].

If indices_or_sections is a tensor, it must be a zero-dimensional or one-dimensional long tensor on the CPU.

dim (int, optional) – dimension along which to split the tensor. Default: 0


In [ ]:
# Example 1 - working

x = torch.arange(6)
torch.tensor_split(x, 3)

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - initial_seed

Returns the initial seed for generating random numbers as a Python long.

Return type:
int

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/zamaniziba18/01-tensor-operations


'https://jovian.ai/zamaniziba18/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://www.w3schools.com/python/python_strings_slicing.asp
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
